name: dart_git
description: A pure dart implementation of Git
version: 0.0.2
homepage: https://gitjournal.io
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  args: ^2.3.0
  buffer: ^1.1.1
  charcode: ^1.3.1
  collection: ^1.15.0
  crypto: ^3.0.1
  diff_match_patch: ^0.4.1
  equatable: ^2.0.3
  file: ^6.1.2
  freezed_annotation: ^1.1.0
  lints: ^1.0.1
  meta: ^1.7.0
  os:
    git: https://github.com/GitJournal/os.git
  path: ^1.8.0
  stash_memory: ^4.0.1
  synchronized: ^3.0.0
  tuple: ^2.0.0

dev_dependencies:
  archive: ^3.1.11
  build_runner: ^2.1.7
  dart_code_metrics: ^4.10.1
  freezed: ^1.1.1
  import_sorter: ^4.6.0
  process_run: ^0.12.3+2
  test: ^1.20.1

import_sorter:
  comments: false
